# Generated by Django 2.2.6 on 2019-12-08 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoice_buttons',
            new_name='MultipleChoice',
        ),
        migrations.CreateModel(
            name='InformationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('user_text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_form.Question_txt')),
            ],
        ),
    ]
