# Generated by Django 3.0 on 2019-12-08 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0002_auto_20191207_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='votes',
            new_name='user_choice',
        ),
        migrations.CreateModel(
            name='IntegerRangeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_int', models.IntegerField()),
                ('user_int', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_form.Question_txt')),
            ],
            bases=(models.Model, django.db.models.fields.IntegerField),
        ),
    ]
