# Generated by Django 2.2.6 on 2019-12-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0003_auto_20191208_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntegerRangeField',
        ),
    ]
