# Generated by Django 2.2.6 on 2019-12-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0004_delete_integerrangefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=200)),
                ('agency', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_form.EvaluationScheme')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.SmallIntegerField(choices=[(0, 'Good'), (1, 'Bad'), (2, 'Dunno')])),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_form.Evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_form.EvaluationQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback_form.EvaluationScheme'),
        ),
    ]
