# Generated by Django 2.2.6 on 2019-12-11 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_form', '0005_auto_20191210_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationanswer',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='evaluationanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='evaluationquestion',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='informationfield',
            name='question',
        ),
        migrations.RemoveField(
            model_name='multiplechoice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='EvaluationAnswer',
        ),
        migrations.DeleteModel(
            name='EvaluationQuestion',
        ),
        migrations.DeleteModel(
            name='EvaluationScheme',
        ),
        migrations.DeleteModel(
            name='InformationField',
        ),
        migrations.DeleteModel(
            name='MultipleChoice',
        ),
        migrations.DeleteModel(
            name='Question_txt',
        ),
    ]
